#!/usr/bin/env python3
"""
Автоматическое объединение всех сгенерированных вопросов

Этот скрипт содержит embedded JSON данные от всех агентов
и автоматически объединяет их в один файл.
"""

import json
from pathlib import Path
from collections import Counter
from datetime import datetime

# ============================================================================
# EMBEDDED JSON DATA FROM AGENTS (Generated by Claude Opus 4)
# ============================================================================

# ПРИМЕЧАНИЕ: Данные будут добавлены после первого запуска
# Скрипт создаст структуру для ручного заполнения

def load_generated_blocks():
    """
    Загрузить все блоки вопросов

    ВАЖНО: После первого запуска заполни переменные ниже
    JSON данными из Task outputs
    """

    # TODO: Скопируй JSON arrays из Task outputs в эти переменные
    blocks = {
        "EDGE": [],  # 75 questions from Task output 1
        "SHADOW": [],  # 40 questions from Task output 2
        "CORE": [],  # 25 questions from Task output 3
        "HEALING": [],  # 60 questions from Task output 4
        "EMOTIONS": [],  # 50 questions from Task output 5
        "RELATIONSHIPS": [],  # 50 questions from Task output 6
        "GOALS": [],  # 50 questions from Task output 7
        "FEARS": [],  # 30 questions from Task output 8
        "VALUES": [],  # 30 questions from Task output 9
        "ENTRY": [],  # 50 questions from Task output 10
        "DEEPENING": [],  # 100 questions from Task output 11
        "INTEGRATING": [],  # 50 questions from Task output 12
        "TRANSFORMING": []  # 30 questions from Task output 13
    }

    return blocks


def merge_all_questions(blocks):
    """Объединить все блоки в один список"""

    all_questions = []

    for block_name, questions in blocks.items():
        if questions:
            all_questions.extend(questions)
            print(f"  ✅ {block_name}: {len(questions)} вопросов")
        else:
            print(f"  ⚠️ {block_name}: ПУСТОЙ (нужно заполнить)")

    return all_questions


def validate_questions(questions):
    """Базовая валидация вопросов"""

    issues = []

    required_fields = ["id", "text", "classification", "psychology", "processing_hints"]

    for idx, q in enumerate(questions):
        q_id = q.get("id", f"question_{idx}")

        # Проверка обязательных полей
        for field in required_fields:
            if field not in q:
                issues.append(f"{q_id}: missing field '{field}'")

        # Проверка classification
        if "classification" in q:
            cls = q["classification"]
            if "domain" not in cls:
                issues.append(f"{q_id}: missing classification.domain")
            elif cls["domain"] in ["patterns", "past_present", "evolution", "lessons", "contradictions"]:
                # Исправляем нестандартные домены из INTEGRATING
                issues.append(f"{q_id}: non-standard domain '{cls['domain']}' (needs mapping)")

    return issues


def fix_integrating_domains(questions):
    """Исправить нестандартные домены в INTEGRATING вопросах"""

    domain_mapping = {
        "patterns": "IDENTITY",
        "past_present": "PAST",
        "contradictions": "IDENTITY",
        "lessons": "GROWTH",
        "evolution": "GROWTH"
    }

    fixed_count = 0

    for q in questions:
        cls = q.get("classification", {})
        domain = cls.get("domain")

        if domain in domain_mapping:
            old_domain = domain
            cls["domain"] = domain_mapping[domain]
            fixed_count += 1
            print(f"    Fixed {q['id']}: {old_domain} → {cls['domain']}")

    if fixed_count > 0:
        print(f"  ✅ Исправлено {fixed_count} доменов")

    return questions


def calculate_statistics(questions):
    """Подсчитать статистику"""

    stats = {
        "total": len(questions),
        "domains": Counter(),
        "depth_levels": Counter(),
        "energy_dynamics": Counter(),
        "journey_stages": Counter(),
        "complexity": Counter(),
        "trust_requirement": Counter()
    }

    for q in questions:
        cls = q.get("classification", {})
        psy = q.get("psychology", {})

        stats["domains"][cls.get("domain")] += 1
        stats["depth_levels"][cls.get("depth_level")] += 1
        stats["energy_dynamics"][cls.get("energy_dynamic")] += 1
        stats["journey_stages"][cls.get("journey_stage")] += 1
        stats["complexity"][psy.get("complexity")] += 1
        stats["trust_requirement"][psy.get("trust_requirement")] += 1

    return stats


def print_statistics(stats):
    """Вывести статистику"""

    print("\n" + "="*80)
    print("📊 СТАТИСТИКА СГЕНЕРИРОВАННЫХ ВОПРОСОВ")
    print("="*80)
    print(f"\nВсего вопросов: {stats['total']}\n")

    print("🏷️  DOMAINS:")
    for domain, count in sorted(stats["domains"].items(), key=lambda x: x[1], reverse=True):
        pct = count / stats["total"] * 100
        print(f"  {domain:20s} {count:3d} ({pct:5.1f}%)")

    print("\n📊 DEPTH LEVELS:")
    for depth, count in sorted(stats["depth_levels"].items(), key=lambda x: x[1], reverse=True):
        pct = count / stats["total"] * 100
        print(f"  {depth:20s} {count:3d} ({pct:5.1f}%)")

    print("\n⚡ ENERGY DYNAMICS:")
    for energy, count in sorted(stats["energy_dynamics"].items(), key=lambda x: x[1], reverse=True):
        pct = count / stats["total"] * 100
        print(f"  {energy:20s} {count:3d} ({pct:5.1f}%)")

    print("\n🚀 JOURNEY STAGES:")
    for stage, count in sorted(stats["journey_stages"].items(), key=lambda x: x[1], reverse=True):
        pct = count / stats["total"] * 100
        print(f"  {stage:20s} {count:3d} ({pct:5.1f}%)")


def save_merged_file(questions, stats):
    """Сохранить объединенный файл"""

    result = {
        "metadata": {
            "version": "2.0",
            "title": "AI Generated Questions - Missing Categories",
            "generation_date": datetime.now().strftime("%Y-%m-%d"),
            "generation_model": "claude-opus-4",
            "total_questions": len(questions),
            "categories": {
                "depth_levels": dict(stats["depth_levels"]),
                "energy_dynamics": dict(stats["energy_dynamics"]),
                "journey_stages": dict(stats["journey_stages"]),
                "domains": dict(stats["domains"])
            }
        },
        "questions": questions
    }

    project_root = Path(__file__).parent.parent
    output_file = project_root / "intelligent_question_core" / "data" / "generated_questions_v2.json"

    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(result, f, indent=2, ensure_ascii=False)

    print(f"\n💾 Сохранено в: {output_file}")
    print(f"📊 Размер файла: {output_file.stat().st_size / 1024:.1f} KB")

    return output_file


def main():
    """Главная функция"""

    print("🚀 Автоматическое объединение сгенерированных вопросов\n")

    # 1. Загрузить блоки
    print("📖 Загрузка блоков...")
    blocks = load_generated_blocks()

    # Проверка что данные заполнены
    empty_blocks = [name for name, data in blocks.items() if not data]
    if empty_blocks:
        print(f"\n⚠️ ВНИМАНИЕ: Следующие блоки ПУСТЫЕ:")
        for block in empty_blocks:
            print(f"  - {block}")
        print(f"\n📝 Отредактируй скрипт и добавь JSON данные в переменные blocks[]")
        print(f"   Данные находятся в Task outputs выше в терминале")
        return

    # 2. Объединить
    print("\n🔄 Объединение блоков...")
    all_questions = merge_all_questions(blocks)

    if not all_questions:
        print("\n❌ Нет вопросов для объединения!")
        return

    # 3. Исправить нестандартные домены
    print("\n🔧 Исправление нестандартных доменов...")
    all_questions = fix_integrating_domains(all_questions)

    # 4. Валидация
    print("\n✅ Валидация...")
    issues = validate_questions(all_questions)

    if issues:
        print(f"\n⚠️ Найдено проблем: {len(issues)}")
        for issue in issues[:10]:
            print(f"  - {issue}")
        if len(issues) > 10:
            print(f"  ... и еще {len(issues) - 10} проблем")
    else:
        print("  ✅ Все вопросы валидны!")

    # 5. Статистика
    print("\n📊 Подсчет статистики...")
    stats = calculate_statistics(all_questions)
    print_statistics(stats)

    # 6. Сохранить
    print("\n💾 Сохранение...")
    output_file = save_merged_file(all_questions, stats)

    print("\n" + "="*80)
    print("✅ ГОТОВО!")
    print("="*80)
    print(f"\nСгенерировано: {len(all_questions)} вопросов")
    print(f"Файл: {output_file}")
    print(f"\nСледующий шаг:")
    print(f"  python3 scripts/validate_questions_completeness.py")


if __name__ == "__main__":
    main()
